---
  - name: Setup LEMP + ELK
    hosts: common elk lemp
    become: yes

    roles: 
      - { role: elk,    when: "'elk'    in {{ group_names }} " }


# Known issues:
# - annoying ansible warning "[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: 'group' in {{ group_names }}"
# - the roles needs some improvements