---
- name: Установить UFW
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Разрешить нужные порты
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 22
    - 80
    - 443
    - 5044 # ELK beats
    - 9200 # ELK elasticsearch
    - 5601 # ELK web
    - 7890 # goaccess

- name: Закрыть все порты по умолчанию
  ufw:
    rule: deny
    direction: in

- name: Включить UFW
  ufw:
    state: enabled
    # enabled: yes

- name: reloaded UFW
  ufw:
    state: reloaded
    # enabled: yes

